version: "3"

services:

  rest:
    env_file: ./.env
    build:
      context: .
    ports:
      - 0.0.0.0:8080:8080
    volumes:
      - rest:/var/opt/gnmatcher
    command:
      - rest
      - --port
      - "8080"
      - --debug
volumes:
  rest:

