version: "3"

services:

  app:
    env_file: ./.env
    build:
      context: .
    ports:
      - 0.0.0.0:8778:8778
    volumes:
      - gnmatcher:/var/opt/gnmatcher
    command:
      - grpc
      - -p
      - "8778"
      - -d

volumes:
  gnmatcher:

