// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protob.proto

package protob

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MatchType int32

const (
	MatchType_NONE           MatchType = 0
	MatchType_CANONICAL      MatchType = 1
	MatchType_CANONICAL_FULL MatchType = 2
	MatchType_VIRUS          MatchType = 3
	MatchType_FUZZY          MatchType = 4
	MatchType_PARTIAL        MatchType = 5
	MatchType_PARTIAL_FUZZY  MatchType = 6
)

var MatchType_name = map[int32]string{
	0: "NONE",
	1: "CANONICAL",
	2: "CANONICAL_FULL",
	3: "VIRUS",
	4: "FUZZY",
	5: "PARTIAL",
	6: "PARTIAL_FUZZY",
}

var MatchType_value = map[string]int32{
	"NONE":           0,
	"CANONICAL":      1,
	"CANONICAL_FULL": 2,
	"VIRUS":          3,
	"FUZZY":          4,
	"PARTIAL":        5,
	"PARTIAL_FUZZY":  6,
}

func (x MatchType) String() string {
	return proto.EnumName(MatchType_name, int32(x))
}

func (MatchType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{0}
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{0}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type Pong struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Version struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Build                string   `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{2}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Version) GetBuild() string {
	if m != nil {
		return m.Build
	}
	return ""
}

type Name struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{3}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Names struct {
	Names                []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Names) Reset()         { *m = Names{} }
func (m *Names) String() string { return proto.CompactTextString(m) }
func (*Names) ProtoMessage()    {}
func (*Names) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{4}
}

func (m *Names) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Names.Unmarshal(m, b)
}
func (m *Names) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Names.Marshal(b, m, deterministic)
}
func (m *Names) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Names.Merge(m, src)
}
func (m *Names) XXX_Size() int {
	return xxx_messageInfo_Names.Size(m)
}
func (m *Names) XXX_DiscardUnknown() {
	xxx_messageInfo_Names.DiscardUnknown(m)
}

var xxx_messageInfo_Names proto.InternalMessageInfo

func (m *Names) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type Output struct {
	Results              []*Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{5}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

type Result struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MatchType            MatchType    `protobuf:"varint,3,opt,name=match_type,json=matchType,proto3,enum=protob.MatchType" json:"match_type,omitempty"`
	MatchData            []*MatchItem `protobuf:"bytes,4,rep,name=match_data,json=matchData,proto3" json:"match_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{6}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Result) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Result) GetMatchType() MatchType {
	if m != nil {
		return m.MatchType
	}
	return MatchType_NONE
}

func (m *Result) GetMatchData() []*MatchItem {
	if m != nil {
		return m.MatchData
	}
	return nil
}

type MatchItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MatchStr             string   `protobuf:"bytes,2,opt,name=match_str,json=matchStr,proto3" json:"match_str,omitempty"`
	EditDistance         int32    `protobuf:"varint,3,opt,name=edit_distance,json=editDistance,proto3" json:"edit_distance,omitempty"`
	EditDistanceStem     int32    `protobuf:"varint,4,opt,name=edit_distance_stem,json=editDistanceStem,proto3" json:"edit_distance_stem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchItem) Reset()         { *m = MatchItem{} }
func (m *MatchItem) String() string { return proto.CompactTextString(m) }
func (*MatchItem) ProtoMessage()    {}
func (*MatchItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{7}
}

func (m *MatchItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchItem.Unmarshal(m, b)
}
func (m *MatchItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchItem.Marshal(b, m, deterministic)
}
func (m *MatchItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchItem.Merge(m, src)
}
func (m *MatchItem) XXX_Size() int {
	return xxx_messageInfo_MatchItem.Size(m)
}
func (m *MatchItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchItem.DiscardUnknown(m)
}

var xxx_messageInfo_MatchItem proto.InternalMessageInfo

func (m *MatchItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MatchItem) GetMatchStr() string {
	if m != nil {
		return m.MatchStr
	}
	return ""
}

func (m *MatchItem) GetEditDistance() int32 {
	if m != nil {
		return m.EditDistance
	}
	return 0
}

func (m *MatchItem) GetEditDistanceStem() int32 {
	if m != nil {
		return m.EditDistanceStem
	}
	return 0
}

func init() {
	proto.RegisterEnum("protob.MatchType", MatchType_name, MatchType_value)
	proto.RegisterType((*Void)(nil), "protob.Void")
	proto.RegisterType((*Pong)(nil), "protob.Pong")
	proto.RegisterType((*Version)(nil), "protob.Version")
	proto.RegisterType((*Name)(nil), "protob.Name")
	proto.RegisterType((*Names)(nil), "protob.Names")
	proto.RegisterType((*Output)(nil), "protob.Output")
	proto.RegisterType((*Result)(nil), "protob.Result")
	proto.RegisterType((*MatchItem)(nil), "protob.MatchItem")
}

func init() { proto.RegisterFile("protob.proto", fileDescriptor_e471450a6e94b5eb) }

var fileDescriptor_e471450a6e94b5eb = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x53, 0x4f, 0x6b, 0xdb, 0x4e,
	0x10, 0xf5, 0xda, 0x92, 0x6c, 0x8d, 0xff, 0xfc, 0x94, 0xe1, 0x77, 0x10, 0x6e, 0x0b, 0x66, 0x5b,
	0x8a, 0x69, 0x4b, 0x1a, 0xdc, 0x53, 0x8f, 0x22, 0x69, 0x8a, 0xc1, 0x91, 0x8d, 0x1c, 0x1b, 0x9a,
	0x8b, 0x58, 0x47, 0x4b, 0x2a, 0xb0, 0x24, 0x23, 0xad, 0x02, 0xfe, 0x0c, 0xbd, 0xf4, 0xdb, 0xf4,
	0xeb, 0x95, 0xdd, 0x95, 0xe4, 0xba, 0x3d, 0x69, 0xde, 0xcc, 0x7b, 0xb3, 0x6f, 0x97, 0x27, 0x18,
	0x1c, 0xf2, 0x4c, 0x64, 0xbb, 0x4b, 0xf5, 0x41, 0x4b, 0x23, 0x6a, 0x81, 0xb1, 0xcd, 0xe2, 0x88,
	0xbe, 0x04, 0x63, 0x95, 0xa5, 0x4f, 0xf8, 0x3f, 0x98, 0xcf, 0x6c, 0x5f, 0x72, 0x97, 0x4c, 0xc8,
	0xd4, 0x0e, 0x34, 0xa0, 0x9f, 0xa1, 0xbb, 0xe5, 0x79, 0x11, 0x67, 0x29, 0xba, 0xd0, 0x7d, 0xd6,
	0x65, 0x45, 0xa9, 0xa1, 0x94, 0xee, 0xca, 0x78, 0x1f, 0xb9, 0x6d, 0x2d, 0x55, 0x80, 0x8e, 0xc1,
	0xf0, 0x59, 0xc2, 0x11, 0xc1, 0x48, 0x59, 0x52, 0xef, 0x55, 0x35, 0x7d, 0x05, 0xa6, 0x9c, 0x15,
	0x52, 0x2a, 0x1b, 0x85, 0x4b, 0x26, 0x1d, 0x29, 0x55, 0x80, 0xce, 0xc0, 0x5a, 0x96, 0xe2, 0x50,
	0x0a, 0x9c, 0x42, 0x37, 0xe7, 0x45, 0xb9, 0x17, 0x9a, 0xd1, 0x9f, 0x8d, 0x2e, 0xab, 0xdb, 0x04,
	0xaa, 0x1d, 0xd4, 0x63, 0xfa, 0x93, 0x80, 0xa5, 0x7b, 0x38, 0x82, 0x76, 0x1c, 0x55, 0xe7, 0xb5,
	0xe3, 0xa8, 0x71, 0xd0, 0x3e, 0x39, 0xc0, 0x2b, 0x80, 0x84, 0x89, 0xc7, 0xef, 0xa1, 0x38, 0x1e,
	0xb8, 0xdb, 0x99, 0x90, 0xe9, 0x68, 0x76, 0x51, 0xef, 0xbe, 0x93, 0x93, 0xfb, 0xe3, 0x81, 0x07,
	0x76, 0x52, 0x97, 0x27, 0x45, 0xc4, 0x04, 0x73, 0x0d, 0xe5, 0xe6, 0x5c, 0x31, 0x17, 0x3c, 0xa9,
	0x14, 0x37, 0x4c, 0x30, 0xfa, 0x83, 0x80, 0xdd, 0x0c, 0xfe, 0x71, 0xf5, 0x02, 0x34, 0x35, 0x2c,
	0x44, 0x5e, 0x59, 0xeb, 0xa9, 0xc6, 0x5a, 0xe4, 0xf8, 0x1a, 0x86, 0x3c, 0x8a, 0x45, 0x18, 0xc5,
	0x85, 0x60, 0xe9, 0xa3, 0x76, 0x68, 0x06, 0x03, 0xd9, 0xbc, 0xa9, 0x7a, 0xf8, 0x01, 0xf0, 0x8c,
	0x14, 0x16, 0x82, 0x27, 0xae, 0xa1, 0x98, 0xce, 0x9f, 0xcc, 0xb5, 0xe0, 0xc9, 0xbb, 0xb4, 0x32,
	0xa3, 0x2e, 0xd3, 0x03, 0xc3, 0x5f, 0xfa, 0x5f, 0x9c, 0x16, 0x0e, 0xc1, 0xbe, 0xf6, 0xfc, 0xa5,
	0x3f, 0xbf, 0xf6, 0x16, 0x0e, 0x41, 0x84, 0x51, 0x03, 0xc3, 0xdb, 0xcd, 0x62, 0xe1, 0xb4, 0xd1,
	0x06, 0x73, 0x3b, 0x0f, 0x36, 0x6b, 0xa7, 0x23, 0xcb, 0xdb, 0xcd, 0xc3, 0xc3, 0x37, 0xc7, 0xc0,
	0x3e, 0x74, 0x57, 0x5e, 0x70, 0x3f, 0xf7, 0x16, 0x8e, 0x89, 0x17, 0x30, 0xac, 0x40, 0xa8, 0xe7,
	0xd6, 0xec, 0x17, 0x01, 0xfb, 0xab, 0xaf, 0x8e, 0xe4, 0x39, 0xbe, 0x01, 0x63, 0x15, 0xa7, 0x4f,
	0x38, 0xa8, 0x5f, 0x4c, 0x86, 0x6f, 0xdc, 0x20, 0x19, 0x41, 0xda, 0xc2, 0xb7, 0xd0, 0xd9, 0xf2,
	0xfc, 0x2f, 0xd2, 0x7f, 0x0d, 0xd2, 0x79, 0xa3, 0x2d, 0x7c, 0x0f, 0x3d, 0xb5, 0xd8, 0xcb, 0x8f,
	0x38, 0xac, 0xc7, 0x2a, 0x51, 0xe3, 0x26, 0x20, 0x3a, 0x41, 0xb4, 0x85, 0x1f, 0xa1, 0x7f, 0x57,
	0xbd, 0x2b, 0x67, 0xc9, 0x69, 0xb9, 0xe4, 0x8f, 0xcf, 0x10, 0x6d, 0x4d, 0xc9, 0x15, 0xd9, 0xe9,
	0x5f, 0xe4, 0xd3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xa5, 0xd5, 0x74, 0x39, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GNMatcherClient is the client API for GNMatcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GNMatcherClient interface {
	Ping(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Pong, error)
	Ver(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Version, error)
	MatchAry(ctx context.Context, in *Names, opts ...grpc.CallOption) (*Output, error)
	MatchStream(ctx context.Context, opts ...grpc.CallOption) (GNMatcher_MatchStreamClient, error)
}

type gNMatcherClient struct {
	cc *grpc.ClientConn
}

func NewGNMatcherClient(cc *grpc.ClientConn) GNMatcherClient {
	return &gNMatcherClient{cc}
}

func (c *gNMatcherClient) Ping(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/protob.GNMatcher/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNMatcherClient) Ver(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Version, error) {
	out := new(Version)
	err := c.cc.Invoke(ctx, "/protob.GNMatcher/Ver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNMatcherClient) MatchAry(ctx context.Context, in *Names, opts ...grpc.CallOption) (*Output, error) {
	out := new(Output)
	err := c.cc.Invoke(ctx, "/protob.GNMatcher/MatchAry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNMatcherClient) MatchStream(ctx context.Context, opts ...grpc.CallOption) (GNMatcher_MatchStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GNMatcher_serviceDesc.Streams[0], "/protob.GNMatcher/MatchStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &gNMatcherMatchStreamClient{stream}
	return x, nil
}

type GNMatcher_MatchStreamClient interface {
	Send(*Name) error
	Recv() (*Name, error)
	grpc.ClientStream
}

type gNMatcherMatchStreamClient struct {
	grpc.ClientStream
}

func (x *gNMatcherMatchStreamClient) Send(m *Name) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gNMatcherMatchStreamClient) Recv() (*Name, error) {
	m := new(Name)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GNMatcherServer is the server API for GNMatcher service.
type GNMatcherServer interface {
	Ping(context.Context, *Void) (*Pong, error)
	Ver(context.Context, *Void) (*Version, error)
	MatchAry(context.Context, *Names) (*Output, error)
	MatchStream(GNMatcher_MatchStreamServer) error
}

func RegisterGNMatcherServer(s *grpc.Server, srv GNMatcherServer) {
	s.RegisterService(&_GNMatcher_serviceDesc, srv)
}

func _GNMatcher_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNMatcherServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protob.GNMatcher/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNMatcherServer).Ping(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNMatcher_Ver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNMatcherServer).Ver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protob.GNMatcher/Ver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNMatcherServer).Ver(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNMatcher_MatchAry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Names)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNMatcherServer).MatchAry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protob.GNMatcher/MatchAry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNMatcherServer).MatchAry(ctx, req.(*Names))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNMatcher_MatchStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GNMatcherServer).MatchStream(&gNMatcherMatchStreamServer{stream})
}

type GNMatcher_MatchStreamServer interface {
	Send(*Name) error
	Recv() (*Name, error)
	grpc.ServerStream
}

type gNMatcherMatchStreamServer struct {
	grpc.ServerStream
}

func (x *gNMatcherMatchStreamServer) Send(m *Name) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gNMatcherMatchStreamServer) Recv() (*Name, error) {
	m := new(Name)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GNMatcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protob.GNMatcher",
	HandlerType: (*GNMatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GNMatcher_Ping_Handler,
		},
		{
			MethodName: "Ver",
			Handler:    _GNMatcher_Ver_Handler,
		},
		{
			MethodName: "MatchAry",
			Handler:    _GNMatcher_MatchAry_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MatchStream",
			Handler:       _GNMatcher_MatchStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protob.proto",
}
